/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Games controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, Game } from "../models";

@Injectable({ providedIn: "root" })
export class GamesService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    gamesList(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<Game>>;
    gamesList(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<Game>>>;
    gamesList(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<Game>>>;
    gamesList(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/games/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    gamesCreate(id: number, local_goals: number, visitant_goals: number, status: string, date: string, match: number, local_team: number, visitant_team: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Game>;
    gamesCreate(id: number, local_goals: number, visitant_goals: number, status: string, date: string, match: number, local_team: number, visitant_team: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Game>>;
    gamesCreate(id: number, local_goals: number, visitant_goals: number, status: string, date: string, match: number, local_team: number, visitant_team: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Game>>;
    gamesCreate(id: number, local_goals: number, visitant_goals: number, status: string, date: string, match: number, local_team: number, visitant_team: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/games/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (id !== undefined) {
            formData.append('id', String(id));
        }
        if (local_goals !== undefined) {
            formData.append('local_goals', String(local_goals));
        }
        if (visitant_goals !== undefined) {
            formData.append('visitant_goals', String(visitant_goals));
        }
        if (status !== undefined) {
            formData.append('status', String(status));
        }
        if (date !== undefined) {
            formData.append('date', String(date));
        }
        if (match !== undefined) {
            formData.append('match', String(match));
        }
        if (local_team !== undefined) {
            formData.append('local_team', String(local_team));
        }
        if (visitant_team !== undefined) {
            formData.append('visitant_team', String(visitant_team));
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formData, requestOptions);
    }

    gamesRetrieve(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Game>;
    gamesRetrieve(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Game>>;
    gamesRetrieve(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Game>>;
    gamesRetrieve(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/games/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    gamesUpdate(id: number, local_goals: number, visitant_goals: number, status: string, date: string, match: number, local_team: number, visitant_team: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Game>;
    gamesUpdate(id: number, local_goals: number, visitant_goals: number, status: string, date: string, match: number, local_team: number, visitant_team: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Game>>;
    gamesUpdate(id: number, local_goals: number, visitant_goals: number, status: string, date: string, match: number, local_team: number, visitant_team: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Game>>;
    gamesUpdate(id: number, local_goals: number, visitant_goals: number, status: string, date: string, match: number, local_team: number, visitant_team: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/games/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (id !== undefined) {
            formData.append('id', String(id));
        }
        if (local_goals !== undefined) {
            formData.append('local_goals', String(local_goals));
        }
        if (visitant_goals !== undefined) {
            formData.append('visitant_goals', String(visitant_goals));
        }
        if (status !== undefined) {
            formData.append('status', String(status));
        }
        if (date !== undefined) {
            formData.append('date', String(date));
        }
        if (match !== undefined) {
            formData.append('match', String(match));
        }
        if (local_team !== undefined) {
            formData.append('local_team', String(local_team));
        }
        if (visitant_team !== undefined) {
            formData.append('visitant_team', String(visitant_team));
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, formData, requestOptions);
    }

    gamesPartialUpdate(id: number, local_goals?: number, visitant_goals?: number, status?: string, date?: string, match?: number, local_team?: number, visitant_team?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Game>;
    gamesPartialUpdate(id: number, local_goals?: number, visitant_goals?: number, status?: string, date?: string, match?: number, local_team?: number, visitant_team?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Game>>;
    gamesPartialUpdate(id: number, local_goals?: number, visitant_goals?: number, status?: string, date?: string, match?: number, local_team?: number, visitant_team?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Game>>;
    gamesPartialUpdate(id: number, local_goals?: number, visitant_goals?: number, status?: string, date?: string, match?: number, local_team?: number, visitant_team?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/games/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (id !== undefined) {
            formData.append('id', String(id));
        }
        if (local_goals !== undefined) {
            formData.append('local_goals', String(local_goals));
        }
        if (visitant_goals !== undefined) {
            formData.append('visitant_goals', String(visitant_goals));
        }
        if (status !== undefined) {
            formData.append('status', String(status));
        }
        if (date !== undefined) {
            formData.append('date', String(date));
        }
        if (match !== undefined) {
            formData.append('match', String(match));
        }
        if (local_team !== undefined) {
            formData.append('local_team', String(local_team));
        }
        if (visitant_team !== undefined) {
            formData.append('visitant_team', String(visitant_team));
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.patch(url, formData, requestOptions);
    }

    gamesDestroy(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    gamesDestroy(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    gamesDestroy(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    gamesDestroy(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/games/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
