/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Gameevents controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, GameEvent } from "../models";

@Injectable({ providedIn: "root" })
export class GameeventsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    gameeventsList(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<GameEvent>>;
    gameeventsList(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<GameEvent>>>;
    gameeventsList(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<GameEvent>>>;
    gameeventsList(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/gameevents/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    gameeventsCreate(id: number, typeEvent: string, minute: number, game: number, player: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<GameEvent>;
    gameeventsCreate(id: number, typeEvent: string, minute: number, game: number, player: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GameEvent>>;
    gameeventsCreate(id: number, typeEvent: string, minute: number, game: number, player: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GameEvent>>;
    gameeventsCreate(id: number, typeEvent: string, minute: number, game: number, player: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/gameevents/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (id !== undefined) {
            formData.append('id', String(id));
        }
        if (typeEvent !== undefined) {
            formData.append('typeEvent', String(typeEvent));
        }
        if (minute !== undefined) {
            formData.append('minute', String(minute));
        }
        if (game !== undefined) {
            formData.append('game', String(game));
        }
        if (player !== undefined) {
            formData.append('player', String(player));
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formData, requestOptions);
    }

    gameeventsRetrieve(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<GameEvent>;
    gameeventsRetrieve(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GameEvent>>;
    gameeventsRetrieve(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GameEvent>>;
    gameeventsRetrieve(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/gameevents/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    gameeventsUpdate(id: number, typeEvent: string, minute: number, game: number, player: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<GameEvent>;
    gameeventsUpdate(id: number, typeEvent: string, minute: number, game: number, player: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GameEvent>>;
    gameeventsUpdate(id: number, typeEvent: string, minute: number, game: number, player: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GameEvent>>;
    gameeventsUpdate(id: number, typeEvent: string, minute: number, game: number, player: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/gameevents/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (id !== undefined) {
            formData.append('id', String(id));
        }
        if (typeEvent !== undefined) {
            formData.append('typeEvent', String(typeEvent));
        }
        if (minute !== undefined) {
            formData.append('minute', String(minute));
        }
        if (game !== undefined) {
            formData.append('game', String(game));
        }
        if (player !== undefined) {
            formData.append('player', String(player));
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, formData, requestOptions);
    }

    gameeventsPartialUpdate(id: number, typeEvent?: string, minute?: number, game?: number, player?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<GameEvent>;
    gameeventsPartialUpdate(id: number, typeEvent?: string, minute?: number, game?: number, player?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GameEvent>>;
    gameeventsPartialUpdate(id: number, typeEvent?: string, minute?: number, game?: number, player?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GameEvent>>;
    gameeventsPartialUpdate(id: number, typeEvent?: string, minute?: number, game?: number, player?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/gameevents/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (id !== undefined) {
            formData.append('id', String(id));
        }
        if (typeEvent !== undefined) {
            formData.append('typeEvent', String(typeEvent));
        }
        if (minute !== undefined) {
            formData.append('minute', String(minute));
        }
        if (game !== undefined) {
            formData.append('game', String(game));
        }
        if (player !== undefined) {
            formData.append('player', String(player));
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.patch(url, formData, requestOptions);
    }

    gameeventsDestroy(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    gameeventsDestroy(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    gameeventsDestroy(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    gameeventsDestroy(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/gameevents/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
