/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated service exports
* Do not edit this file manually
*/
export { AuthService } from "./auth.service";
export { GameeventsService } from "./gameevents.service";
export { GamesService } from "./games.service";
export { MatchesService } from "./matches.service";
export { PlayersService } from "./players.service";
export { SchemaService } from "./schema.service";
export { TeamsService } from "./teams.service";
export { TournamentsService } from "./tournaments.service";
