/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Matches controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, Match } from "../models";

@Injectable({ providedIn: "root" })
export class MatchesService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    matchesList(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<Match>>;
    matchesList(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<Match>>>;
    matchesList(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<Match>>>;
    matchesList(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/matches/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    matchesCreate(id: number, number: number, start_date: string, tournament: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Match>;
    matchesCreate(id: number, number: number, start_date: string, tournament: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Match>>;
    matchesCreate(id: number, number: number, start_date: string, tournament: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Match>>;
    matchesCreate(id: number, number: number, start_date: string, tournament: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/matches/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (id !== undefined) {
            formData.append('id', String(id));
        }
        if (number !== undefined) {
            formData.append('number', String(number));
        }
        if (start_date !== undefined) {
            formData.append('start_date', String(start_date));
        }
        if (tournament !== undefined) {
            formData.append('tournament', String(tournament));
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formData, requestOptions);
    }

    matchesRetrieve(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Match>;
    matchesRetrieve(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Match>>;
    matchesRetrieve(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Match>>;
    matchesRetrieve(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/matches/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    matchesUpdate(id: number, number: number, start_date: string, tournament: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Match>;
    matchesUpdate(id: number, number: number, start_date: string, tournament: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Match>>;
    matchesUpdate(id: number, number: number, start_date: string, tournament: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Match>>;
    matchesUpdate(id: number, number: number, start_date: string, tournament: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/matches/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (id !== undefined) {
            formData.append('id', String(id));
        }
        if (number !== undefined) {
            formData.append('number', String(number));
        }
        if (start_date !== undefined) {
            formData.append('start_date', String(start_date));
        }
        if (tournament !== undefined) {
            formData.append('tournament', String(tournament));
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, formData, requestOptions);
    }

    matchesPartialUpdate(id: number, number?: number, start_date?: string, tournament?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Match>;
    matchesPartialUpdate(id: number, number?: number, start_date?: string, tournament?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Match>>;
    matchesPartialUpdate(id: number, number?: number, start_date?: string, tournament?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Match>>;
    matchesPartialUpdate(id: number, number?: number, start_date?: string, tournament?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/matches/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (id !== undefined) {
            formData.append('id', String(id));
        }
        if (number !== undefined) {
            formData.append('number', String(number));
        }
        if (start_date !== undefined) {
            formData.append('start_date', String(start_date));
        }
        if (tournament !== undefined) {
            formData.append('tournament', String(tournament));
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.patch(url, formData, requestOptions);
    }

    matchesDestroy(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    matchesDestroy(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    matchesDestroy(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    matchesDestroy(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/matches/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
