/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Players controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, Player } from "../models";

@Injectable({ providedIn: "root" })
export class PlayersService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    playersList(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<Player>>;
    playersList(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<Player>>>;
    playersList(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<Player>>>;
    playersList(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/players/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    playersCreate(id: number, name: string, team?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Player>;
    playersCreate(id: number, name: string, team?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Player>>;
    playersCreate(id: number, name: string, team?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Player>>;
    playersCreate(id: number, name: string, team?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/players/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (id !== undefined) {
            formData.append('id', String(id));
        }
        if (name !== undefined) {
            formData.append('name', String(name));
        }
        if (team !== undefined) {
            formData.append('team', String(team));
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formData, requestOptions);
    }

    playersRetrieve(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Player>;
    playersRetrieve(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Player>>;
    playersRetrieve(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Player>>;
    playersRetrieve(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/players/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    playersUpdate(id: number, name: string, team?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Player>;
    playersUpdate(id: number, name: string, team?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Player>>;
    playersUpdate(id: number, name: string, team?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Player>>;
    playersUpdate(id: number, name: string, team?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/players/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (id !== undefined) {
            formData.append('id', String(id));
        }
        if (name !== undefined) {
            formData.append('name', String(name));
        }
        if (team !== undefined) {
            formData.append('team', String(team));
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, formData, requestOptions);
    }

    playersPartialUpdate(id: number, name?: string, team?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Player>;
    playersPartialUpdate(id: number, name?: string, team?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Player>>;
    playersPartialUpdate(id: number, name?: string, team?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Player>>;
    playersPartialUpdate(id: number, name?: string, team?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/players/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (id !== undefined) {
            formData.append('id', String(id));
        }
        if (name !== undefined) {
            formData.append('name', String(name));
        }
        if (team !== undefined) {
            formData.append('team', String(team));
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.patch(url, formData, requestOptions);
    }

    playersDestroy(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    playersDestroy(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    playersDestroy(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    playersDestroy(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/players/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
