/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Teams controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, Team } from "../models";

@Injectable({ providedIn: "root" })
export class TeamsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    teamsList(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<Team>>;
    teamsList(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<Team>>>;
    teamsList(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<Team>>>;
    teamsList(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/teams/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    teamsCreate(id: number, name: string, tournament: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Team>;
    teamsCreate(id: number, name: string, tournament: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Team>>;
    teamsCreate(id: number, name: string, tournament: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Team>>;
    teamsCreate(id: number, name: string, tournament: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/teams/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (id !== undefined) {
            formData.append('id', String(id));
        }
        if (name !== undefined) {
            formData.append('name', String(name));
        }
        if (tournament !== undefined) {
            formData.append('tournament', String(tournament));
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formData, requestOptions);
    }

    teamsRetrieve(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Team>;
    teamsRetrieve(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Team>>;
    teamsRetrieve(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Team>>;
    teamsRetrieve(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/teams/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    teamsUpdate(id: number, name: string, tournament: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Team>;
    teamsUpdate(id: number, name: string, tournament: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Team>>;
    teamsUpdate(id: number, name: string, tournament: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Team>>;
    teamsUpdate(id: number, name: string, tournament: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/teams/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (id !== undefined) {
            formData.append('id', String(id));
        }
        if (name !== undefined) {
            formData.append('name', String(name));
        }
        if (tournament !== undefined) {
            formData.append('tournament', String(tournament));
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, formData, requestOptions);
    }

    teamsPartialUpdate(id: number, name?: string, tournament?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Team>;
    teamsPartialUpdate(id: number, name?: string, tournament?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Team>>;
    teamsPartialUpdate(id: number, name?: string, tournament?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Team>>;
    teamsPartialUpdate(id: number, name?: string, tournament?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/teams/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (id !== undefined) {
            formData.append('id', String(id));
        }
        if (name !== undefined) {
            formData.append('name', String(name));
        }
        if (tournament !== undefined) {
            formData.append('tournament', String(tournament));
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.patch(url, formData, requestOptions);
    }

    teamsDestroy(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    teamsDestroy(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    teamsDestroy(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    teamsDestroy(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/teams/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
