/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Tournaments controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, Tournament } from "../models";

@Injectable({ providedIn: "root" })
export class TournamentsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    tournamentsList(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<Tournament>>;
    tournamentsList(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<Tournament>>>;
    tournamentsList(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<Tournament>>>;
    tournamentsList(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/tournaments/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    tournamentsCreate(id: number, name: string, city: string, type: string, status: string, start_date: string, end_date: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Tournament>;
    tournamentsCreate(id: number, name: string, city: string, type: string, status: string, start_date: string, end_date: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Tournament>>;
    tournamentsCreate(id: number, name: string, city: string, type: string, status: string, start_date: string, end_date: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Tournament>>;
    tournamentsCreate(id: number, name: string, city: string, type: string, status: string, start_date: string, end_date: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/tournaments/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (id !== undefined) {
            formData.append('id', String(id));
        }
        if (name !== undefined) {
            formData.append('name', String(name));
        }
        if (city !== undefined) {
            formData.append('city', String(city));
        }
        if (type !== undefined) {
            formData.append('type', String(type));
        }
        if (status !== undefined) {
            formData.append('status', String(status));
        }
        if (start_date !== undefined) {
            formData.append('start_date', String(start_date));
        }
        if (end_date !== undefined) {
            formData.append('end_date', String(end_date));
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formData, requestOptions);
    }

    tournamentsRetrieve(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<Tournament>;
    tournamentsRetrieve(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Tournament>>;
    tournamentsRetrieve(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Tournament>>;
    tournamentsRetrieve(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/tournaments/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    tournamentsUpdate(id: number, name: string, city: string, type: string, status: string, start_date: string, end_date: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Tournament>;
    tournamentsUpdate(id: number, name: string, city: string, type: string, status: string, start_date: string, end_date: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Tournament>>;
    tournamentsUpdate(id: number, name: string, city: string, type: string, status: string, start_date: string, end_date: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Tournament>>;
    tournamentsUpdate(id: number, name: string, city: string, type: string, status: string, start_date: string, end_date: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/tournaments/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (id !== undefined) {
            formData.append('id', String(id));
        }
        if (name !== undefined) {
            formData.append('name', String(name));
        }
        if (city !== undefined) {
            formData.append('city', String(city));
        }
        if (type !== undefined) {
            formData.append('type', String(type));
        }
        if (status !== undefined) {
            formData.append('status', String(status));
        }
        if (start_date !== undefined) {
            formData.append('start_date', String(start_date));
        }
        if (end_date !== undefined) {
            formData.append('end_date', String(end_date));
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, formData, requestOptions);
    }

    tournamentsPartialUpdate(id: number, name?: string, city?: string, type?: string, status?: string, start_date?: string, end_date?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Tournament>;
    tournamentsPartialUpdate(id: number, name?: string, city?: string, type?: string, status?: string, start_date?: string, end_date?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Tournament>>;
    tournamentsPartialUpdate(id: number, name?: string, city?: string, type?: string, status?: string, start_date?: string, end_date?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Tournament>>;
    tournamentsPartialUpdate(id: number, name?: string, city?: string, type?: string, status?: string, start_date?: string, end_date?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/tournaments/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (id !== undefined) {
            formData.append('id', String(id));
        }
        if (name !== undefined) {
            formData.append('name', String(name));
        }
        if (city !== undefined) {
            formData.append('city', String(city));
        }
        if (type !== undefined) {
            formData.append('type', String(type));
        }
        if (status !== undefined) {
            formData.append('status', String(status));
        }
        if (start_date !== undefined) {
            formData.append('start_date', String(start_date));
        }
        if (end_date !== undefined) {
            formData.append('end_date', String(end_date));
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.patch(url, formData, requestOptions);
    }

    tournamentsDestroy(id: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    tournamentsDestroy(id: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    tournamentsDestroy(id: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    tournamentsDestroy(id: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/tournaments/${id}/`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
