/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface AuthToken {
    username: string;
    password: string;
    readonly token: string;
}

export interface Game {
    readonly id: number;
    local_goals: number;
    visitant_goals: number;
    status: string;
    date: string;
    match: number;
    local_team: number;
    visitant_team: number;
}

export interface GameEvent {
    readonly id: number;
    typeEvent: string;
    minute: number;
    game: number;
    player: number;
}

export interface Match {
    readonly id: number;
    number: number;
    start_date: string;
    tournament: number;
}

export interface PatchedGame {
    readonly id?: number;
    local_goals?: number;
    visitant_goals?: number;
    status?: string;
    date?: string;
    match?: number;
    local_team?: number;
    visitant_team?: number;
}

export interface PatchedGameEvent {
    readonly id?: number;
    typeEvent?: string;
    minute?: number;
    game?: number;
    player?: number;
}

export interface PatchedMatch {
    readonly id?: number;
    number?: number;
    start_date?: string;
    tournament?: number;
}

export interface PatchedPlayer {
    readonly id?: number;
    name?: string;
    team?: number;
}

export interface PatchedTeam {
    readonly id?: number;
    name?: string;
    tournament?: number;
}

export interface PatchedTournament {
    readonly id?: number;
    name?: string;
    city?: string;
    type?: string;
    status?: string;
    start_date?: string;
    end_date?: string;
}

export interface Player {
    readonly id: number;
    name: string;
    team?: number;
}

export interface Team {
    readonly id: number;
    name: string;
    tournament: number;
}

export interface Tournament {
    readonly id: number;
    name: string;
    city: string;
    type: string;
    status: string;
    start_date: string;
    end_date: string;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
