# Generated by Django 5.2.13 on 2026-04-18 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_game_player_gameevent_team_player_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameevent',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameevent',
            name='player',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameEvent',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
