# Generated by Django 5.2.13 on 2026-04-18 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_goals', models.IntegerField()),
                ('visitant_goals', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('local_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_games', to='teams.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.match')),
                ('visitant_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitant_games', to='teams.team')),
            ],
        ),
    ]
