# Generated by Django 5.2.13 on 2026-05-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
