# Generated by Django 5.2.13 on 2026-05-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('tournaments', '0003_remove_gameevent_game_remove_gameevent_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='tournament',
        ),
        migrations.AddField(
            model_name='team',
            name='tournaments',
            field=models.ManyToManyField(blank=True, related_name='teams', to='tournaments.tournament'),
        ),
    ]
